import {
  Activity,
  Blocks,
  Bot,
  Boxes,
  Building2,
  Cable,
  Code2,
  Database,
  Gauge,
  Globe,
  LayoutDashboard,
  LifeBuoy,
  LifeBuoy as Rescue,
  Palette,
  Plug,
  Rocket,
  Search,
  Server,
  ShoppingBag,
  Smartphone,
  Target,
  Truck,
  Users,
  Wrench,
  type LucideIcon,
} from "lucide-react";

/** Иконка страницы. Ключ — id из content/pages/*.json. */
export const pageIcons: Record<string, LucideIcon> = {
  "razrabotka-sajtov": Globe,
  "internet-magazin": ShoppingBag,
  "veb-prilozheniya": LayoutDashboard,
  "mobilnye-prilozheniya": Smartphone,
  "dorabotka-sajta": Wrench,
  "spasenie-proekta": Rescue,
  "podderzhka-sajta": LifeBuoy,
  "redizajn-sajta": Palette,
  "perenos-sajta": Truck,
  "audit-sajta": Search,
  "uskorenie-sajta": Gauge,
  "tehnicheskaya-optimizaciya": Activity,
  analitika: Activity,
  integracii: Cable,
  avtomatizaciya: Bot,
  "api-i-backend": Server,
  "vydelennaya-komanda": Users,
  "korporativnyj-sajt": Building2,
  lending: Target,
  "sajt-vizitka": Globe,
  "promo-sajt": Rocket,
  marketplejs: Boxes,
  "b2b-portal": Boxes,
  "lichnyj-kabinet": Users,
  "admin-panel": LayoutDashboard,
  "crm-sistema": Database,
  "erp-sistema": Database,
  saas: Blocks,
  pwa: Smartphone,
  "audit-koda": Code2,
  parsing: Database,
  "chat-bot": Bot,
  mikroservisy: Blocks,
  highload: Server,
};

export function pageIcon(id: string): LucideIcon {
  return pageIcons[id] ?? Plug;
}
